### PR TITLE
Added tests from `bll_compatibility` folder

### LINKED ISSUE #71: The whole folder of test is unused: bll_compatibility
There is a folder `bll_compatibility` which contains dozen of tests and they are not run.

### PR DESCRIPTION
**Pull request by Kojoley**
Closes #71

### CODE REVIEW

**Comment by Kojoley** [comment]
I am not sure those tests are needed, they test Lambda (only few were converted to test Phoenix, I spotted it too late).

**Comment by Flast** [comment]
Indeed. We can comment out the tests.

**Comment by Flast** [comment]
Ah, OK I understood. A simple lambda, such as just a placeholder, will pass through its arguments **as reference** and dangling reference in `apply1` (return a reference to argument). So, can you comment out the line, @Kojoley ?

**Comment by Kojoley** [comment]
> Ah, OK I understood. A simple lambda, such as just a placeholder, will pass through its arguments as reference and dangling reference in `apply1` (return a reference to argument).

`A` is `int&`, the argument is a variable `one`, if it returns a reference it should be a reference to `one`.

> So, can you comment out the line, @Kojoley ?

Again, the whole file tests Lambda, not Phoenix, what is the point? I can just leave only `algorithm_test` and `bind_tests_advanced` as they were converted to test Phoenix.

**Comment by Flast** [comment]
> > Ah, OK I understood. A simple lambda, such as just a placeholder, will pass through its arguments as reference and dangling reference in `apply1` (return a reference to argument).
> 
> `A` is `int&`, the argument is a variable `one`, if it returns a reference it should be a reference to `one`.

No, `A` is `int` because of  `apply1 **<int>** (_1, one)`.

> > So, can you comment out the line, @Kojoley ?
> 
> Again, the whole file tests Lambda, not Phoenix, what is the point? I can just leave only `algorithm_test` and `bind_tests_advanced` as they were converted to test Phoenix.

Fair enough.

**Comment by Flast** [comment]
I'm so sorry for leaving this PR (I kind of remember I waited CI completion...).

**Pull request merged**
