### PR TITLE
Conditionally replace deprecated/removed std::random_shuffle by adapt…

### PR DESCRIPTION
**Pull request by DanielaE**
…ing std::shuffle.

Signed-off-by: Daniela Engert <dani@ngrt.de>

### CODE REVIEW

**Comment by Flast** [comment]
`phoenix::random_shuffle` should be just a lazy version of std's, i.e. implement and providing `phoenix::shuffle` is better.

**Comment by Flast** [comment]
Also, I'm planning to provide newcomer (not only shuffle) algorithms to next release, ;)

**Comment by djowel** [comment]
wonderful!

**Comment by DanielaE** [comment]
Great!

Pleace bear in mind, users of msvc 14.x (i.e. VS2015 and VS2017) in compilation modes "later than C++14" need my proposed patch at least as an interim solution because std::random_shuffle is gone without a trace.

**Pull request closed without merging**
