### PR TITLE
C++11 variadics

### PR DESCRIPTION
**Pull request by Flast**
I know this PR is very very huge, but there is no new changes, except remove unused headers (325604c3f02af16be62a4623b3556c8f11659d48), regenerate preprocessed files (0d3abcc997190176be814cf9e74e086e76262c3d) and changelog (d85b8323e8fa61a82f80c9c2ef65e39c3540643a).

This is not a breaking change, i.e. no user code should be changed.

I tested on
- GCC 6.1.1 20160721 (Red Hat 6.1.1-4)
    - gnu++98 / 11 / 14 mode
- clang 3.8.0
    - gnu++98 / 11 / 14 mode
- MSVC
    - (WIP)

I list all previous PRs for variadics.
- #19 Prepare variadics
- #21 Variadics: core/actor
- #22 Restore copyright notice
- #23 Variadics: core/call
- #24 Implement C++11 variadic templates based function_equal
- #25 Implement variadic based phx2_result
- #26 variadics: core/function_eval
- #27 C++11 variadics based core/expression
- #29 variadics: prepare for other components
- #30 variadics: bind component
- #31 variadics: scope component
- #32 variadics: expr macros

I'll wait merging until it is approved.

### CODE REVIEW

**Comment by Flast** [comment]
Newer MSVC shows much of regressions. So, I'll fix those until 1.62 beta close.

**Comment by Lastique** [comment]
Please, revert the change from develop (or fix it if it's quicker) because it breaks a lot of Boost.Log tests and seeing test results during the release cycle is essential.

http://www.boost.org/development/tests/develop/developer/output/teeks99-09e-win2012R2-64on64-boost-bin-v2-libs-log-test-~hdr-expressions-attr~hpp-test-msvc-12-0-dbg-adrs-mdl-64-thrd-mlt.html

**Comment by djowel** [comment]
Ouch. @Flast, tell me if it's an easy fix, or we can revert for now.

**Comment by Flast** [comment]
I think revert is good for now.

**Comment by Flast** [comment]
done. I'll investigate this weekend.

**Pull request merged**
